#!/usr/bin/sh

# Throws error if we exit with a nonzero status
set -e

FILE="notes/project_planning.txt"

if [ -e "$FILE" ]; then
  echo "ERROR: $FILE exists. Encrypt and delete it with \`sh scripts/encryption/encrypt.sh\`."
  exit 1
fi
