#!/usr/bin/env dash

# In the past, I had some pre-commit scripts, but right 
# now I don't. I'm sure I'll find some other uses in the
# future for this space :). So I'm keeping this here.

echo "#############################"
echo "Pre-commit hooks have passed."
echo "#############################"

echo "#########################"
echo "Status before committing:"

git status

echo "#########################"
