#!/usr/bin/env dash

DIR="docs/private"

if [ -e "$DIR" ]; then
  printf "%s%s\n" \
         "ERROR: $DIR exists. Encrypt and delete it with " \
         "\`dash programs/sh/encryption/encrypt.sh\`."
  exit 1
fi

echo "#############################"
echo "Pre-commit hooks have passed."
echo "#############################"

echo "#########################"
echo "Status before committing:"

git status

echo "#########################"
