FROM docker.io/library/debian:sid as builder

RUN apt update

COPY run_guix_shell.sh run_guix_shell.sh

RUN mkdir base
COPY secrets.env base/secrets.env

# https://guix.gnu.org/manual/en/html_node/Binary-Installation.html
RUN apt install -y guix git

ARG BRANCH_NAME=main
ENV BRANCH_NAME=$BRANCH_NAME
RUN git clone --branch $BRANCH_NAME https://github.com/RyanOatmeal/RyanOatmeal.git base/RyanOatmeal

# https://guix.gnu.org/manual/en/html_node/Build-Environment-Setup.html
RUN groupadd --system guixbuild
RUN for i in $(seq -w 1 10);             \
    do                                   \
      useradd -g guixbuild -G guixbuild  \
      -d /var/empty -s $(which nologin)  \
      -c "Guix build usuer $i" --system  \
      guixbuilduser$i;                   \
    done

CMD ["guix-daemon", "--build-users-group=guixbuild"]