FROM docker.io/library/debian:sid as builder

RUN apt update
COPY run_container.sh run_container.sh


# https://guix.gnu.org/manual/en/html_node/Binary-Installation.html
RUN apt install -y guix

# https://guix.gnu.org/manual/en/html_node/Build-Environment-Setup.html
RUN groupadd --system guixbuild
RUN for i in $(seq -w 1 10);             \
    do                                   \
      useradd -g guixbuild -G guixbuild  \
      -d /var/empty -s $(which nologin)  \
      -c "Guix build usuer $i" --system  \
      guixbuilduser$i;                   \
    done